export const DEFAULT_REQUEST_TIMEOUT_MS = 90_000;
export const MASTER_DATA_REQUEST_TIMEOUT_MS = 240_000;
export const MASTER_DATA_TEST_TIMEOUT_MS = 480_000;
export const MASTER_DATA_MAX_RESPONSE_TIME_MS = 240_000;
export const MIS_SLOW_REQUEST_TIMEOUT_MS = 120_000;
export const BILLING_REQUEST_TIMEOUT_MS = 180_000;
export const BILLING_MAX_RESPONSE_TIME_MS = 240_000;
export const BILLING_TEST_TIMEOUT_MS = 600_000;
export const CONSUMPTION_REQUEST_TIMEOUT_MS = 360_000;
export const CONSUMPTION_MAX_RESPONSE_TIME_MS = 360_000;
export const CONSUMPTION_TEST_TIMEOUT_MS = 600_000;
export const DEFAULT_TEST_TIMEOUT_MS = 240_000;
/** HES meter jobs can stay RUNNING several minutes under load — avoid 120s defaults. */
export const HES_COMMANDS_JOB_POLL_TIMEOUT_MS = 360_000;
export const HES_COMMANDS_JOB_POLL_INTERVAL_MS = 3_000;
export const HES_COMMANDS_JOB_POLL_INITIAL_DELAY_MS = 5_000;
/** Minimum gap between HES job POSTs when tests share one meter (ms). */
export const HES_COMMANDS_JOB_MIN_GAP_MS = 10_000;
/** Poll window + init POST + validation buffer for @e2e command specs. */
export const HES_COMMANDS_E2E_TEST_TIMEOUT_MS = 540_000;
export const HES_COMMANDS_PAYMENT_TEST_TIMEOUT_MS = HES_COMMANDS_E2E_TEST_TIMEOUT_MS;
export const TECHNICAL_ANALYSIS_REQUEST_TIMEOUT_MS = 120_000;
export const TECHNICAL_ANALYSIS_MAX_RESPONSE_TIME_MS = 120_000;
export const ASSET_MANAGEMENT_HIERARCHY_REQUEST_TIMEOUT_MS = 180_000;
export const ASSET_MANAGEMENT_COVERAGE_TEST_TIMEOUT_MS = 900_000;
