import fs from "fs";
import path from "path";
import type { TestInfo } from "@playwright/test";
import type { ValidationResult } from "../models/resultModel";

export interface DefectReportContext {
  endpoint: string;
  method?: string;
  requestParams?: unknown;
  responseStatus?: number;
  responseBody?: unknown;
  /** What the backend contract / repository logic expects */
  expectedBehavior?: string;
  module?: string;
}

export interface DefectReportInput {
  apiName: string;
  responseTimeMs: number;
  results: ValidationResult[];
  context: DefectReportContext;
  testTitle?: string;
}

const DEFECTS_DIR = path.join(process.cwd(), "reports", "defects");

function sanitizeFileName(value: string): string {
  return value.replace(/[^a-zA-Z0-9-_]+/g, "-").replace(/-+/g, "-");
}

function truncateJson(value: unknown, maxLength = 6000): string {
  const text = JSON.stringify(value, null, 2);
  if (text.length <= maxLength) {
    return text;
  }
  return `${text.slice(0, maxLength)}\n... (truncated)`;
}

export class DeveloperReportEngine {
  static buildMarkdown(input: DefectReportInput): string {
    const failed = input.results.filter((r) => r.status === "FAIL");
    const passed = input.results.filter((r) => r.status === "PASS");
    const firstFailure = failed[0];
    const baseUrl = process.env.BASE_URL ?? "(not set)";
    const timestamp = new Date().toISOString();

    return `# API defect report (for backend developer)

> Automation failed on a **business/API contract** check. This usually indicates a backend, SQL, or response-mapping issue — not a test-script typo.

## At a glance

| Field | Value |
|-------|-------|
| **API** | ${input.apiName} |
| **Test** | ${input.testTitle ?? "—"} |
| **Endpoint** | ${input.context.method ?? "GET"} ${input.context.endpoint} |
| **Base URL** | ${baseUrl} |
| **Response time** | ${input.responseTimeMs} ms |
| **HTTP status** | ${input.context.responseStatus ?? "—"} |
| **Failed checks** | ${failed.length} / ${input.results.length} |
| **First failure** | ${firstFailure?.name ?? "—"} |
| **Run at** | ${timestamp} |

## Failure detail

\`\`\`
${firstFailure?.message ?? "No error message captured"}
\`\`\`

${
  input.context.expectedBehavior
    ? `## Expected behavior (from backend / contract)

${input.context.expectedBehavior}
`
    : ""
}

## Request sent by automation

\`\`\`json
${truncateJson(input.context.requestParams ?? {})}
\`\`\`

## API response (excerpt)

\`\`\`json
${truncateJson(input.context.responseBody ?? {})}
\`\`\`

## All failed validations

${failed.map((f, i) => `${i + 1}. **${f.name}** — ${f.message ?? "no message"}`).join("\n")}

## Passed checks before failure

${passed.map((p) => `- ${p.name}`).join("\n") || "_None_"}

## Suggested steps for developer

1. Reproduce with the same query params (Postman/curl) against \`${baseUrl}${input.context.endpoint}\`.
2. Compare response with the **Expected behavior** section above.
3. Trace the repository/service method for this report and confirm SQL filters + DTO field names.
4. Fix backend logic or API serialization; re-run: \`npx playwright test --grep "${input.apiName}"\`.

---
*Generated by Indoore API automation — share this file in Jira/Azure DevOps/GitHub issue.*
`;
  }

  static write(input: DefectReportInput): string {
    if (!fs.existsSync(DEFECTS_DIR)) {
      fs.mkdirSync(DEFECTS_DIR, { recursive: true });
    }

    const stamp = new Date().toISOString().replace(/[:.]/g, "-");
    const fileName = `${sanitizeFileName(input.apiName)}-${stamp}.md`;
    const filePath = path.join(DEFECTS_DIR, fileName);
    const markdown = this.buildMarkdown(input);

    fs.writeFileSync(filePath, markdown, "utf8");
    return filePath;
  }

  static async attachToTest(
    testInfo: TestInfo,
    filePath: string,
    markdown: string,
  ): Promise<void> {
    await testInfo.attach("developer-defect-report.md", {
      body: markdown,
      contentType: "text/markdown",
    });

    await testInfo.attach("developer-defect-report.json", {
      body: JSON.stringify(
        {
          reportFile: filePath,
          hint: "Share developer-defect-report.md with the backend team",
        },
        null,
        2,
      ),
      contentType: "application/json",
    });
  }
}
