import fs from "fs";
import path from "path";
import type { TestInfo } from "@playwright/test";
import type { ValidationResult } from "../models/resultModel";
import type {
  DefectReportContext,
  DefectTriageResult,
} from "../ai/defect-triage.types";
import { buildHeuristicTriage } from "../ai/defect-heuristic-triage";
import { enrichDefectTriage, isDefectLlmEnabled } from "../ai/defect-llm-triage";

export type { DefectReportContext };

export interface DefectReportInput {
  apiName: string;
  responseTimeMs: number;
  results: ValidationResult[];
  context: DefectReportContext;
  testTitle?: string;
  triage?: DefectTriageResult;
}

const DEFECTS_DIR = path.join(process.cwd(), "reports", "defects");

function sanitizeFileName(value: string): string {
  return value.replace(/[^a-zA-Z0-9-_]+/g, "-").replace(/-+/g, "-");
}

function truncateJson(value: unknown, maxLength = 6000): string {
  const text = JSON.stringify(value, null, 2);
  if (text.length <= maxLength) {
    return text;
  }
  return `${text.slice(0, maxLength)}\n... (truncated)`;
}

function renderTriageSection(triageResult?: DefectTriageResult): string {
  if (!triageResult) {
    return "";
  }

  const { triage, source, model, error } = triageResult;
  const steps = triage.nextSteps.map((s, i) => `${i + 1}. ${s}`).join("\n");
  const tags = triage.tags.length ? triage.tags.join(", ") : "—";

  return `## AI / heuristic triage

| Field | Value |
|-------|-------|
| **Suggested title** | ${triage.title} |
| **Severity** | ${triage.severity} |
| **Classification** | ${triage.classification} |
| **Likely owner** | ${triage.likelyOwner} |
| **Confidence** | ${triage.confidence} |
| **Source** | ${source}${model ? ` (${model})` : ""} |

${triage.summary}

### Recommended next steps

${steps}

**Tags:** ${tags}
${error ? `\n> Triage note: LLM enrichment failed — used heuristic. (${error})\n` : ""}
`;
}

export class DeveloperReportEngine {
  static buildMarkdown(input: DefectReportInput): string {
    const failed = input.results.filter((r) => r.status === "FAIL");
    const passed = input.results.filter((r) => r.status === "PASS");
    const firstFailure = failed[0];
    const baseUrl = process.env.BASE_URL ?? "(not set)";
    const timestamp = new Date().toISOString();
    const triageResult =
      input.triage ??
      buildHeuristicTriage({
        apiName: input.apiName,
        results: input.results,
        context: input.context,
        testTitle: input.testTitle,
      });

    return `# API defect report (for backend developer)

> Automation failed on a **business/API contract** check. This usually indicates a backend, SQL, or response-mapping issue — not a test-script typo.

## At a glance

| Field | Value |
|-------|-------|
| **API** | ${input.apiName} |
| **Test** | ${input.testTitle ?? "—"} |
| **Endpoint** | ${input.context.method ?? "GET"} ${input.context.endpoint} |
| **Base URL** | ${baseUrl} |
| **Response time** | ${input.responseTimeMs} ms |
| **HTTP status** | ${input.context.responseStatus ?? "—"} |
| **Failed checks** | ${failed.length} / ${input.results.length} |
| **First failure** | ${firstFailure?.name ?? "—"} |
| **Run at** | ${timestamp} |

${renderTriageSection(triageResult)}
## Failure detail

\`\`\`
${firstFailure?.message ?? "No error message captured"}
\`\`\`

${
  input.context.expectedBehavior
    ? `## Expected behavior (from backend / contract)

${input.context.expectedBehavior}
`
    : ""
}

## Request sent by automation

\`\`\`json
${truncateJson(input.context.requestParams ?? {})}
\`\`\`

## API response (excerpt)

\`\`\`json
${truncateJson(input.context.responseBody ?? {})}
\`\`\`

## All failed validations

${failed.map((f, i) => `${i + 1}. **${f.name}** — ${f.message ?? "no message"}`).join("\n")}

## Passed checks before failure

${passed.map((p) => `- ${p.name}`).join("\n") || "_None_"}

## Suggested steps for developer

1. Reproduce with the same query params (Postman/curl) against \`${baseUrl}${input.context.endpoint}\`.
2. Compare response with the **Expected behavior** / **AI triage** sections above.
3. Trace the repository/service method for this report and confirm SQL filters + DTO field names.
4. Fix backend logic or API serialization; re-run: \`npx playwright test --grep "${input.apiName}"\`.

---
*Generated by Indoore API automation — share this file in Jira/Azure DevOps/GitHub issue.*
`;
  }

  static resolveTriageSync(input: Omit<DefectReportInput, "triage">): DefectTriageResult {
    return buildHeuristicTriage({
      apiName: input.apiName,
      results: input.results,
      context: input.context,
      testTitle: input.testTitle,
    });
  }

  static async resolveTriage(
    input: Omit<DefectReportInput, "triage">,
  ): Promise<DefectTriageResult> {
    return enrichDefectTriage({
      apiName: input.apiName,
      results: input.results,
      context: input.context,
      testTitle: input.testTitle,
    });
  }

  static write(input: DefectReportInput): { reportPath: string; triagePath: string } {
    if (!fs.existsSync(DEFECTS_DIR)) {
      fs.mkdirSync(DEFECTS_DIR, { recursive: true });
    }

    const stamp = new Date().toISOString().replace(/[:.]/g, "-");
    const baseName = `${sanitizeFileName(input.apiName)}-${stamp}`;
    const reportPath = path.join(DEFECTS_DIR, `${baseName}.md`);
    const triagePath = path.join(DEFECTS_DIR, `${baseName}.triage.json`);

    const triage =
      input.triage ??
      this.resolveTriageSync(input);
    const markdown = this.buildMarkdown({ ...input, triage });

    fs.writeFileSync(reportPath, markdown, "utf8");
    fs.writeFileSync(
      triagePath,
      JSON.stringify(
        {
          apiName: input.apiName,
          testTitle: input.testTitle,
          endpoint: input.context.endpoint,
          responseStatus: input.context.responseStatus,
          ...triage,
        },
        null,
        2,
      ),
      "utf8",
    );

    return { reportPath, triagePath };
  }

  /** Writes heuristic report immediately; optionally enriches with LLM and rewrites. */
  static async writeWithOptionalLlm(
    input: Omit<DefectReportInput, "triage">,
  ): Promise<{ reportPath: string; triagePath: string; triage: DefectTriageResult }> {
    const triage = isDefectLlmEnabled()
      ? await this.resolveTriage(input)
      : this.resolveTriageSync(input);

    const paths = this.write({ ...input, triage });
    return { ...paths, triage };
  }

  static async attachToTest(
    testInfo: TestInfo,
    reportPath: string,
    markdown: string,
    triagePath?: string,
    triage?: DefectTriageResult,
  ): Promise<void> {
    await testInfo.attach("developer-defect-report.md", {
      body: markdown,
      contentType: "text/markdown",
    });

    await testInfo.attach("developer-defect-report.json", {
      body: JSON.stringify(
        {
          reportFile: reportPath,
          triageFile: triagePath,
          triage,
          hint: "Share developer-defect-report.md with the backend team",
          llmEnabled: isDefectLlmEnabled(),
        },
        null,
        2,
      ),
      contentType: "application/json",
    });

    if (triage) {
      await testInfo.attach("defect-triage.json", {
        body: JSON.stringify(triage, null, 2),
        contentType: "application/json",
      });
    }
  }
}
