import ExcelJS from "exceljs";
import type { BulkUploadFileInput } from "../Data/bulk-validation.data";
import {
    ensureMeterReplacementBulkRuntimeContext,
} from "./meter-replacement-bulk-runtime.helper";
import type { APIRequestContext } from "@playwright/test";

export async function buildMeterReplacementBulkUpload(
    authenticatedApi: APIRequestContext,
): Promise<BulkUploadFileInput> {

    const runtime =await ensureMeterReplacementBulkRuntimeContext(authenticatedApi,);
    const workbook =new ExcelJS.Workbook();
    workbook.creator ="Playwright Automation";
    workbook.lastModifiedBy ="Playwright Automation";
    workbook.created =new Date();
    workbook.modified =new Date();
    const sheet =workbook.addWorksheet("Meter Replacement",);
    //-------------------------------------------------------
    // Header
    //-------------------------------------------------------
    sheet.columns = [
        {
            header: "Sl No",
            key: "slNo",
            width: 10,
        },
        {
            header: "Consumer ID",
            key: "consumerId",
            width: 20,
        },
        {
            header: "Old Meter Serial",
            key: "oldMeterSerial",
            width: 22,
        },
        {
            header: "New Meter Serial",
            key: "newMeterSerial",
            width: 22,
        },
        {
            header: "Old Meter Reading",
            key: "oldReading",
            width: 18,
        },
        {
            header: "New Meter Reading",
            key: "newReading",
            width: 18,
        },
        {
            header: "Replacement Reason",
            key: "reason",
            width: 35,
        },
        {
            header: "Latitude",
            key: "latitude",
            width: 18,
        },
        {
            header: "Longitude",
            key: "longitude",
            width: 18,
        },
        {
            header: "Remarks",
            key: "remarks",
            width: 35,
        },

    ];

    //-------------------------------------------------------
    // Styling
    //-------------------------------------------------------
    sheet.getRow(1).font = {
        bold: true,
    };
    sheet.getRow(1).alignment = {
        vertical: "middle",
        horizontal: "center",
    };
    //-------------------------------------------------------
    // Dynamic Runtime Row
    //-------------------------------------------------------
    sheet.addRow({
        consumerId:runtime.consumerId,
        oldMeterSerial:runtime.oldMeterSerial,
        newMeterSerial:runtime.newMeterSerial,
        oldReading:0,
        newReading:0,
        reason:"Smart Meter Upgrade",
        latitude: runtime.latitude,
        longitude:runtime.longitude,
        remarks: "Generated by Automation",
    });
    //-------------------------------------------------------
    // Freeze Header
    //-------------------------------------------------------
    sheet.views = [
        {
            state: "frozen",
            ySplit: 1,
        },

    ];
    //-------------------------------------------------------
    // Auto Filter
    //-------------------------------------------------------
    sheet.autoFilter = {
        from: "A1",
        to: "I2",
    };
    //-------------------------------------------------------
    // Convert Workbook -> Buffer
    //-------------------------------------------------------
    const buffer =Buffer.from(await workbook.xlsx.writeBuffer(),);
    return {
        fileName:`meter-replacement-${Date.now()}.xlsx`,
        mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        buffer,
    };
}